apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: karansood07/node-app:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://root:eW91cnBhc3N3b3Jk@mongodb:27017/admin"  
            - name: MONGO_DB_NAME
              value: "mydatabase"  
